
services:
  laravel:
    image: ${IMAGE_LARAVEL:-ivandev284/laravel-notificacion-logger}:latest
    container_name: laravel-app
    restart: unless-stopped
    env_file:
      - ./laravel-notificacion-logger/.env
    ports:
      - "8030:8000"
      - "8001:80"
    depends_on:
      - postgres
      - mongo
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://laravel-app:8000"]
      interval: 30s
      timeout: 10s
      retries: 5

  node-notifications:
    image: ${IMAGE_NODE:-ivandev284/node-notifications}:latest
    container_name: node-notifications
    restart: unless-stopped
    env_file:
      - ./node-notifications/.env
    ports:
      - "3002:3001"
    depends_on:
      - postgres
      - mongo
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: notifications
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  mongo:
    image: mongo:6
    container_name: mongo-db
    restart: unless-stopped
    ports:
      - "27019:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - backend

volumes:
  pgdata:
  mongodata:

networks:
  backend:
    driver: bridge
