name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*.*.*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      REGISTRY: docker.io
      IMAGE_NODE: ${{ secrets.DOCKER_USERNAME }}/node-notifications
      IMAGE_LARAVEL: ${{ secrets.DOCKER_USERNAME }}/laravel-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate .env file for Laravel
        run: |
          cat <<EOF > ./laravel-service/.env
          APP_NAME=Laravel
          APP_ENV=production
          APP_KEY=
          APP_DEBUG=false
          APP_URL=http://localhost

          LOG_CHANNEL=stack

          DB_CONNECTION=pgsql
          DB_HOST=db
          DB_PORT=5432
          DB_DATABASE=${{ secrets.DB_DATABASE }}
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}

          BROADCAST_DRIVER=log
          CACHE_DRIVER=file
          QUEUE_CONNECTION=sync
          SESSION_DRIVER=file
          SESSION_LIFETIME=120
          EOF

      - name: Build and push Node.js image
        uses: docker/build-push-action@v5
        with:
          context: ./node-notifications
          file: ./node-notifications/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NODE }}:latest

      - name: Build and push Laravel image
        uses: docker/build-push-action@v5
        with:
          context: ./laravel-notificacion-logger
          file: ./laravel-notificacion-logger/Dockerfile
          push: true
          tags: ${{ env.IMAGE_LARAVEL }}:latest
          platforms: linux/amd64

      - name: Deploy with Docker Compose
        run: |
          docker compose down || true
          docker compose pull
          docker compose up -d --build